Re-structure the repo and added poetry related files
mat-1/Repldex pull request #63
Opened 2021-01-07 05:13 UTC by leon332157

I have tested this so all of the import works. Not sure entirely if this works on replit, needs more testing.

2021-01-07 05:20 UTC, Codemonkey51 commented
I don't get how just moving almost all the files to an src folder. I agree this repo needs to be rearranged but it should be done differently, like grouping server files into a module, same with discord bot

2021-01-07 05:30 UTC, leon332157 commented
I have tried to do so, with the file structure being very messy, some import does not work. I think I will probably condense the file a little more but having multiple folders doesn't work well with Python imports.

2021-01-07 05:32 UTC, Codemonkey51 commented
> I have tried to do so, with the file structure being very messy, some import does not work. I think I will probably condense the file a little more but having multiple folders doesn't work well with Python imports.

I can try to do my idea locally then if it works pr it :/

2021-01-07 13:01 UTC, leon332157 commented
@Codemonkey51 Have you worked on anything. What we have right now seems fine. I think it's best if we merge this to the master then start from there since we have the plans as to what is going to happen.

2021-01-07 15:53 UTC, Codemonkey51 submitted a review, later dismissed

2021-01-07 15:53 UTC, Codemonkey51 commented on .github/workflows/python-app.yml
> -        pytest
Un-remove pytest please, it is needed for the test suite

2021-01-07 15:54 UTC, mat-1 requested changes
spaces are cringe, use tabs pls

2021-01-07 19:35 UTC, mat-1 requested changes
ok double quotes are cringe as well, use single quotes pls

2021-01-07 19:44 UTC, leon332157 commented
Since there's a bug with black, I'm going to keep it but not enforcing it.

2021-01-08 00:27 UTC, leon332157 commented
nice now pytest technically work. Now it's time to clean up the code more.

2021-01-08 01:33 UTC, mat-1 approved these changes
Looks good!

2021-01-08 01:41 UTC, leon332157 commented
???

2021-01-08 03:09 UTC, Codemonkey51 approved these changes
mat says good so i say good

2021-01-08 03:10 UTC, merged